### ISSUE TITLE
Move configuration data outside of application folder

### ISSUE THREAD

**Issue by CwTiruve** [YunoHost-Apps/prowlarr_ynh#3] opened 2021-12-17 23:53 UTC
Hi,

When I want to update Prowlarr, it's not working, there is the log :

Your Prowlarr configuration '/opt/yunohost/prowlarr/.data' is being stored in application folder '/opt/yunohost/prowlarr' which will cause data lost during the upgrade.

Do you know how can I upgrade prowlarr ?

**Comment by tituspijean** [comment] 2021-12-18 11:35
Duplicate of #2.

**Closed by tituspijean** 2021-12-18 11:35 UTC
