### ISSUE TITLE
Service Failure

### ISSUE THREAD

**Issue by DJPlaya** [YunoHost-Apps/prowlarr_ynh#16] opened 2022-06-27 23:29 UTC
### Describe the bug
The prowlarr daemon fails right after installing.
Accesing the prowlarr website then results in HTTP error 502.

### Context

- Hardware: Raspberry Pi 4
- YunoHost version: 4.3.6.3, fresh installation
- I have access to my server: Through SSH & through the webadmin & direct access via keyboard / screen
- Using, or trying to install package version/branch: Default (develop)
- If upgrading, current package version: 0.1.10.1375~ynh1

### Logs
Service Log:
```
Jun 28 00:20:06 systemd[1]: Started Prowlarr Daemon.
Jun 28 00:20:06 systemd[3355]: prowlarr.service: Failed to execute command: Exec format error
Jun 28 00:20:06 systemd[3355]: prowlarr.service: Failed at step EXEC spawning /opt/yunohost/prowlarr/Prowlarr: Exec format error
Jun 28 00:20:06 systemd[1]: prowlarr.service: Main process exited, code=exited, status=203/EXEC
Jun 28 00:20:06 systemd[1]: prowlarr.service: Failed with result 'exit-code'.
Jun 28 00:20:07 systemd[1]: prowlarr.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 00:20:07 systemd[1]: prowlarr.service: Scheduled restart job, restart counter is at 1.
Jun 28 00:20:07 systemd[1]: Stopped Prowlarr Daemon.
```
There are no other logs to provide, the same error appears when trying to run the file directly from the console

**Comment by tituspijean** [comment] 2022-06-28 11:37
`Exec format error` usually means the binary of the software is meant for another server architecture.

Can you share the app's installation log please, as well as state if you run your RPi4 on x32 or x64 architecture?

**Comment by DJPlaya** [comment] 2022-06-28 15:26
My RPi should run on an 64-bit ARM-Cortex A72.

Here is the install log > https://paste.yunohost.org/raw/ojabutetog

**Comment by tituspijean** [comment] 2022-06-28 16:18
> `YNH_ARCH: armhf`

It looks like your OS is x32 bits, not x64.

This is a duplicate of #11. I will try to fix that ASAP.

**Closed by tituspijean** 2022-06-28 16:18 UTC
